spring.datasource.url=${DB_URL}
server.port=5000
fakestore.api.url=http://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com/products
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
logging.level.root=${LOG_LEVEL-ROOT:INFO}
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
